ministryofjustice/new-nomis-ui

app/containers/Authentication/reducer.js, app/containers/Authentication/tests/reducer.test.js
Will then have access in read only mode.
=> NN-1309 Allow Custodial Manager role to see OMIC / Keyworker icon

package.json, server/api/oauthApi.js, server/auth.js, server/config.js, server/index.js, server/sessionManagementRoutes.js, views/pages/autherror.ejs, yarn.lock
Needs some more environment variables before merging and fix to the cookie session environment variable too
=> NN-1437: Add feature switch for oauth2

notm-specs/src/test/groovy/pages/AddCaseNotePage.groovy, notm-specs/src/test/groovy/specs/CaseNotesSpecification.groovy, notm-specs/src/test/groovy/specs/HomePageSpecification.groovy, notm-specs/src/test/groovy/specs/SearchResultsSpecification.groovy
... and a little bit of tidying up
=> Fix some brittle integration tests

README.md, internals/webpack/webpack.base.babel.js, internals/webpack/webpack.prod.babel.js, package.json, yarn.lock
… so we can check on bundle size easily
=> Removed unused moment locales and added webpack-bundle-analyzer

app/app.scss, app/containers/Bookings/Details/ScheduledEvents/ScheduledEvents.styles.js, app/containers/Bookings/Details/ScheduledEvents/__snapshots__/ScheduledEvents.test.js.snap, app/scss/bootstrap/bootstrap-grid.scss
- Days no longer split between pages
- Prints consistently across browsers
=> NN-1663 Print updates for 7 day schedule

app/components/ActionLinks/index.js, app/components/ActionLinks/tests/index.test.js, app/containers/HomePage/SearchForm.js, app/containers/HomePage/tests/searchForm.test.js
* Point admin-utilities link at omic, not prisonstaffhub
* Fix up global search redirect from home page search form
=> Nn 1684 regression fix

app/components/ActionLinks/index.js, app/containers/Bookings/Results/SearchForm.js, app/containers/HomePage/SearchForm.js
Wording changes
Placeholder removal
=> NN-1718 - Icon reorder

app/customers/hmpps/app/components/Header/header.theme.js, app/customers/hmpps/app/components/Header/index.js
This is a hack - could do with sorting out styles!
=> NN-1724 get working on mobile - need work to GDS styles

app/containers/Bookings/Details/AddCaseNote/index.js
Added the offender name to the Add Case note page.
However, I have raised https://dsdmoj.atlassian.net/browse/NN-1796 to take a look at both this and the Add Appointment pages in more detail as there are a few areas for improvement.
=> NN-1510 Add offender name to Add Case Note page

app/components/Bookings/Details/__snapshots__/header.test.js.snap, app/components/Bookings/Details/header.js, notm-specs/src/test/groovy/pages/OffenderDetailsPage.groovy, notm-specs/src/test/groovy/specs/OffenderDetailsSpecification.groovy
For https://dsdmoj.atlassian.net/browse/NN-1921 
Update the IEP details link to point to the right page. Also update some code variables to match.
=> Update IEP details link

app/components/Bookings/Details/AlertList/desktopAlertsFilterForm.js, app/components/Bookings/Details/AlertList/desktopAlertsFilterForm.scss, app/components/Bookings/Details/AlertList/mobileAlertsFilterForm.js, app/containers/Bookings/Details/CaseNotes/filterForm.js, app/containers/Bookings/Details/CaseNotes/filterForm.scss
The Apply filters button had a random margin applied to it.
Replaced that with a React component using Bootstap's margin
convention.
As a result of updating the CSS, a couple of SCSS files failed linting
due to old code. This also cleans that up.
=> NN-2098: Fix Apply filters button positioning

app/components/Bookings/Details/AlertList/desktopAlertsFilterForm.js, app/components/Bookings/Details/AlertList/index.js, app/components/Bookings/Details/AlertList/mobileAlertsFilterForm.js, app/containers/Bookings/Details/Alerts/index.js
For https://dsdmoj.atlassian.net/browse/NN-2146
=> NN-2146: Change alert date labels and alert creation button text

app/components/Bookings/Details/AlertList/AlertList.test.js, app/components/Bookings/Details/AlertList/index.js, app/containers/Bookings/Details/Alerts/index.js, app/containers/Bookings/sagas.js, app/containers/EliteApiLoader/actions.js
Reverts ministryofjustice/new-nomis-ui#310
=> Revert "Revert "NN-1954 Add close alert button and show notify toast when closed from PSH""

.eslintrc, app/components/Bookings/AlertFlags.js, app/components/Bookings/Details/__snapshots__/header.test.js.snap, app/components/Bookings/Details/header.scss, app/components/Bookings/Details/header.test.js, app/components/Bookings/alertFlags.json, app/containers/Bookings/Results/SearchForm.js, notm-specs/src/test/groovy/specs/SearchResultsSpecification.groovy
Pulls alertFlags in a common JSON config file used for both the display flags and the filter checkboxes. Modifies flag and filter behaviour so on flag/filter could correspond to multiple alert codes - in this case this relates to "Risk to LGBT" which relates to two alert codes but we always want them handled together.
=> Nn 2204 alert flags filter form

app/components/Bookings/Details/__snapshots__/header.test.js.snap, app/components/Bookings/Details/header.scss, app/components/Bookings/Details/header.test.js, app/components/Bookings/alertFlags.json, notm-specs/src/test/groovy/specs/SearchResultsSpecification.groovy
Add Care leaver flag/filter. As per policy, that flag corresponds only to the Care Experienced (LCE) alert code.
=> NN-2208: Add Care leaver alert flag/filter

app/components/Bookings/Details/header.scss, app/containers/Bookings/Results/SearchForm.js
Fixing some icon heights and also filter ordering.
=> NN-2213: Fix icon alignment and filter ordering

app/components/ActionLinks/index.js, app/components/ActionLinks/tests/index.test.js
Reverts ministryofjustice/new-nomis-ui#345
=> Revert "NN-2234 update bulk appointments link"

app/components/ActionLinks/index.js, app/components/ActionLinks/tests/index.test.js
Reverts ministryofjustice/new-nomis-ui#347
=> Revert "Revert "NN-2234 update bulk appointments link""

app/components/ActionLinks/index.js, app/components/ActionLinks/tests/index.test.js
Reverts ministryofjustice/new-nomis-ui#348
=> Revert "Revert "Revert "NN-2234 update bulk appointments link"""

app/components/ActionLinks/index.js, app/components/ActionLinks/tests/index.test.js
Reverts ministryofjustice/new-nomis-ui#349
=> Revert "Revert "Revert "Revert "NN-2234 update bulk appointments link""""

app/components/Page/Page.js, app/containers/Bookings/Results/SearchForm.js, app/containers/HomePage/SearchForm.js, app/containers/HomePage/index.js, app/containers/HomePage/searchForm.scss, app/containers/NotificationBar/NotificationBar.styles.js, notm-specs/src/test/groovy/pages/HomePage.groovy, package.json, yarn.lock
- Remove 'Welcome back'
- Changed field label to be - Prisoner name or number
- Added hint text
- Changed Location label text
- Only 1 H1 element
- Dropped search button to bottom of form
**Before**
**After**
=> NN-2243 Changes to search area on homepage

app/containers/HomePage/SearchForm.js, package.json, yarn.lock
- Reduced some vertical spacing
- Changed 'Location' to 'Residential location'
=> NN-2243 Spacing and wording tweaks for homepage search

app/components/Bookings/Details/__snapshots__/header.test.js.snap, app/components/Bookings/Details/header.js, app/components/Bookings/Details/header.test.js, app/containers/Bookings/Details/header.js, notm-specs/src/test/groovy/specs/OffenderDetailsSpecification.groovy
Reverts ministryofjustice/new-nomis-ui#359
=> Revert "CAT-562 cat manage link - use 'View' text for ordinary users"

app/containers/Bookings/Details/header.js, notm-specs/src/test/groovy/specs/OffenderDetailsSpecification.groovy
Reverts ministryofjustice/new-nomis-ui#356
=> Revert "CAT-562 Reinstate cat manage link for normal staff"

app/components/MobileMenu/index.js, app/containers/App/index.js, app/containers/EliteApiLoader/actions.js, app/containers/Header/index.js, app/containers/MobileMenu/index.js, app/customers/hmpps/app/components/Header/index.js, package.json, yarn.lock
Remove React caseload switching and add link to caseload switching page on prisonstaffhub.
=> NN-2246: Add link to new caseload switching page, remove old React way

helm_deploy/values-dev.yaml, helm_deploy/values-preprod.yaml, helm_deploy/values-prod.yaml, notm-specs/src/test/groovy/mockapis/AllocationManagerApi.groovy, notm-specs/src/test/groovy/specs/HealthSpecification.groovy, package.json, server/api/allocationManagerApi.js, server/apis.js, server/config.js, server/services/healthCheck.js, server/setupHealthChecks.js
This adds integrations with the allocation manager api for dev/pre/prod. Endpoint is not currently in use, but will be used to show POM on the quicklook screen.
=> Nn 2277 allocation management api integration

app/components/Bookings/Details/AlertList/AlertList.test.js, app/components/Bookings/Details/AlertList/index.js
=> NN-2255 edit alert

app/components/Bookings/Details/AlertList/AlertList.test.js, app/components/Bookings/Details/AlertList/index.js
This reverts commit f9f3380fdc3ef9fcdbbce00d05a132604a3b6b94.
=> Revert "Alee/dcs 255 b (#376)"

app/containers/Bookings/Details/QuickLook/index.js, app/containers/Bookings/Details/QuickLook/tests/assigned-staff-members.test.js, app/helpers/dataMappers/quickLook.js, notm-specs/src/test/groovy/mockapis/AllocationManagerApi.groovy, notm-specs/src/test/groovy/specs/AppointmentSpecification.groovy, notm-specs/src/test/groovy/specs/CaseNotesSpecification.groovy, notm-specs/src/test/groovy/specs/LoginSpecification.groovy, notm-specs/src/test/groovy/specs/OffenderDetailsSpecification.groovy, server/services/booking-details.test.js, server/services/booking-keydates.test.js, server/services/booking-quicklook.test.js, server/services/booking.js, server/setupRoutes.js, server/utils.js
Reverts ministryofjustice/new-nomis-ui#379
Integration does not work in Pre and is breaking Quicklook.
=> Revert "NN-2263: Add Prison Offender Manager and Co-working Prison Offender Manager to quicklook"

app/containers/Bookings/Details/OffenderDetails/__snapshots__/index.test.js.snap, app/containers/Bookings/Details/OffenderDetails/index.js, app/containers/Bookings/Details/OffenderDetails/index.test.js, app/containers/Bookings/Details/QuickLook/index.js, app/helpers/dataMappers/offenderDetails.js, notm-specs/src/test/groovy/mockapis/Elite2Api.groovy, notm-specs/src/test/groovy/specs/CaseNotesSpecification.groovy, notm-specs/src/test/groovy/specs/OffenderDetailsSpecification.groovy, notm-specs/src/test/groovy/specs/PaginationSpecification.groovy, notm-specs/src/test/groovy/specs/SearchResultsSpecification.groovy, server/services/booking-details.test.js, server/services/booking-quicklook.test.js, server/services/booking.js
Move identifiers and contacts section with next of kin to the Personal tab.
=> NN-1234 Move prisoner details

docker-compose.yaml, helm_deploy/notm/templates/_envs.tpl, helm_deploy/values-dev.yaml, helm_deploy/values-preprod.yaml, helm_deploy/values-prod.yaml, notm-specs/src/test/groovy/mockapis/Elite2Api.groovy, notm-specs/src/test/groovy/mockapis/WhereaboutsApi.groovy, notm-specs/src/test/groovy/model/TestFixture.groovy, notm-specs/src/test/groovy/specs/AlertsSpecification.groovy, notm-specs/src/test/groovy/specs/CaseNoteFilterSpecification.groovy, notm-specs/src/test/groovy/specs/CaseNotesSpecification.groovy, notm-specs/src/test/groovy/specs/HeaderDropDownSpecification.groovy, notm-specs/src/test/groovy/specs/HealthSpecification.groovy, notm-specs/src/test/groovy/specs/HomePageSpecification.groovy, notm-specs/src/test/groovy/specs/KeyWorkerRoleBasedAccessSpecification.groovy, notm-specs/src/test/groovy/specs/LoginSpecification.groovy, notm-specs/src/test/groovy/specs/MyAllocationsSpecification.groovy, notm-specs/src/test/groovy/specs/OffenderDetailsSpecification.groovy, notm-specs/src/test/groovy/specs/PaginationSpecification.groovy, notm-specs/src/test/groovy/specs/SearchResultsSpecification.groovy, package.json, server/api/eliteApi.js, server/api/whereaboutsApi.js, server/apis.js, server/config.js, server/services/healthCheck.js, server/services/user.js, server/services/user.test.js, server/setupHealthChecks.js, server/setupRoutes.js
The endpoint to check if whereabouts is available has moved from elite2 to whereabouts API.
=> Dt 526 whereabouts switch

app/components/Bookings/Details/__snapshots__/header.test.js.snap, app/components/Bookings/Details/header.scss, app/components/Bookings/Details/header.test.js, app/components/Bookings/alertFlags.json, notm-specs/src/test/groovy/specs/SearchResultsSpecification.groovy
=> NN-2448 Add conflict and no one-to-one alerts

helm_deploy/notm/templates/_envs.tpl, helm_deploy/values-dev.yaml, server/api/dataComplianceApi.js
=> GDPR-78 Switching on retention link in dev

app/components/Bookings/Details/__snapshots__/header.test.js.snap, app/components/Bookings/Details/header.scss, app/components/Bookings/Details/header.test.js, app/components/Bookings/alertFlagValues.js, notm-specs/src/test/groovy/specs/SearchResultsSpecification.groovy
These flags will look like this:
=> DCS-511 Adding additional flags for covid19

helm_deploy/notm/templates/deployment.yaml, helm_deploy/notm/templates/ingress.yaml
=> NN-2720: Revert helm upgrades

helm_deploy/notm/templates/deployment.yaml, helm_deploy/notm/templates/ingress.yaml
Reverts ministryofjustice/new-nomis-ui#472
=> Revert "NN-2720: Revert helm upgrades"

app/containers/Bookings/Details/CaseNotes/AmendCaseNote/AmendCaseNote.js
Updated to follow the same pattern as the create case note page, removing the reliance on existing state and allowing back and forth between this page and server-rendered pages.
=> NN-2756: Fix page render failure when coming from non-react page

app/containers/Authentication/reducer.js, app/containers/Authentication/tests/reducer.test.js
Enable licence link for LICENCE_READONLY role.
=> DCS-317 Read-only role for licences

server/setupRoutes.js
Make sure the URL doesn't gobble up some valid React router urls
=> NN-2704: Fix matching of root offender url

package-lock.json, package.json, server/setupWebSecurity.js
based on this: https://helmetjs.github.io/docs/nocache/
=> DCS-579 Moving away from deprecated nocache and moving to module

helm_deploy/notm/templates/ingress.yaml
Reverts ministryofjustice/new-nomis-ui#507
=> Revert "NN-2906: Use namespace for ingress class"

package-lock.json, package.json
=> NN-2955 Upgrade new-nomis-shared which has footer with Support link removed
